export const LOAD_USER = "LOAD_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const LOAD_SALES = "LOAD_SALES";
export const GET_SALES = "GET_SALES";
export const ADD_SALES = "ADD_SALES";
export const DELETE_SALES = "DELETE_SALES";
export const UPDATE_SALES = "UPDATE_SALES";

export const LOAD_EXPENSES = "LOAD_EXPENSES";
export const GET_EXPENSES = "GET_EXPENSES";
export const CREATE_EXPENSES = "CREATE_EXPENSES";
export const UPDATE_EXPENSES = "UPDATE_EXPENSES";
export const DELETE_EXPENSES = "DELETE_EXPENSES";
